# Generated by Django 4.0 on 2022-01-03 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_profile_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email_id',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='enroll',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='phone_number',
        ),
    ]
